/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_yolov5ncnn_OpenCV */
#include <unistd.h>
#include <cmath>
#include <iostream>
#include <string>

#include "opencv2/opencv.hpp"

#ifndef _Included_com_tencent_yolov5ncnn_OpenCV
#define _Included_com_tencent_yolov5ncnn_OpenCV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_yolov5ncnn_OpenCV
 * Method:    DetectMat
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_tencent_yolov5ncnn_OpenCV_DetectMat
  (JNIEnv *, jclass, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
